### ISSUE TITLE
jah pode al mossar

### ISSUE THREAD

**Issue by fernanduandrade** [mateusmoov/jah-pod-al-mossar#2]
Quando já poder al mossar ter uma img de um prato de comida colorido
Se não poder al mossar ter uma img de um prato de comida preto e branco com um sinal de bloqueado

**Comment by mateusmoov** [comment]
![image](https://github.com/mateusmoov/jah-pod-al-mossar/assets/49696764/f3231276-318f-4550-8f2d-8a7b1891d7fd)
